#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Assign parameters to variables

filepath=$1
ip=$2
username=$3
ssh_key=$4

#Transfer file using scp

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~

#check transfer  status

if [ $? -eq 0 ]
then 
		echo "File Successfully Transfered"
else 
		echo "File not uploaded"
fi
