#!/usr/bin/env bash

# Check if Nginx is already installed
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Installing..."
    sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y || { echo "Failed to install Nginx. Exiting..."; exit 1; }
else
    echo "Nginx is already installed."
fi

# Check if UFW is enabled
if sudo ufw status | grep -q "inactive"; then
    echo "UFW is not enabled. Enabling..."
    sudo ufw enable
fi

# Backup default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Create a new index file
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Set up a redirection to a YouTube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

echo "Nginx setup completed."
