#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
file_h="/etc/passwd"

while IFS=: read -r f1 _ _ f2 _ f3 f4 f5 f6 _ f7 _; do
    echo "The user $f1 is part of the $f2 gang, lives in $f3 and rides $f4. $f5's place is protected by the passcode $f6, more info about the user here: $f7"
done < "$file_h"
